apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab-walkthrough
  labels:
    app.kubernetes.io/part-of: auto-redaction-agent
    app.kubernetes.io/component: workbench
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
