apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: qdrant
  labels:
    app: qdrant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: docker.io/qdrant/qdrant:v1.12.5
          ports:
            - name: http
              containerPort: 6333
            - name: grpc
              containerPort: 6334
          volumeMounts:
            - name: storage
              mountPath: /qdrant/storage
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 4Gi
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: qdrant-storage
