apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: redaction-agent-api
  namespace: redaction-agent
  labels:
    app: redaction-agent
spec:
  to:
    kind: Service
    name: redaction-agent
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
