apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - ../../manifests/minio
  - ../../manifests/mcp-gateway
  - ../../manifests/rhoai-modelservice
  - ../../manifests/agent
  - ../../manifests/web-ui
  - ../../manifests/discovery
  - ../../manifests/observability

labels:
  - pairs:
      app.kubernetes.io/part-of: auto-redaction-agent
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
